name: Test

on: [push, pull_request]

jobs:
  build_job:
    runs-on: fedora_latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: fedora_latest
          - arch: aarch64
            distro: fedora_latest
          - arch: s390x
            distro: fedora_latest
          - arch: ppc64le
            distro: fedora_latest
    steps:
      - uses: actions/checkout@v3.0.2
        with:
          submodules: true
          set-safe-directory: true

      - uses: uraimo/run-on-arch-action@v2.2.0
        name: Build
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          install: |
            yum install -y automake libtool autotools-dev git make gcc libyajl-dev fsverity-utils-devel

          run: |
            find $(pwd) -name '.git' -exec bash -c 'git config --global --add safe.directory ${0%/.git}' {} \;
            ./autogen.sh
            ./configure CFLAGS='-Wall -Werror'
            make -j $(nproc)

  fuzzer:
    runs-on: fedora-latest
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
            yum install -y automake libtool autotools-dev git make gcc libyajl-dev fsverity-utils-devel honggfuzz
            find $(pwd) -name '.git' -exec bash -c 'git config --global --add safe.directory ${0%/.git}' {} \;

    - name: build
      run: |
            ./autogen.sh
            ./configure CFLAGS='-Wall -Werror'
            make -j $(nproc)

    - name: run fuzzer
      run: |
            make -C fuzzing run-ci

  clang-formatter:
    runs-on: fedora-latest
    strategy:
      fail-fast: false
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      run: |
            yum install -y make clang-tools-extra

    - name: check formatting
      run: |
            make -C hacking clang-format
            git diff --exit-code
